import { z } from "zod"

export const themePresetSchema = z.enum(["material3", "cupertino", "custom"])
export type ThemePreset = z.infer<typeof themePresetSchema>

export const stateManagementSchema = z.enum([
    "provider",
    "riverpod",
    "bloc",
    "getx",
    "mobx",
    "none",
])
export type StateManagement = z.infer<typeof stateManagementSchema>

export const backendProviderSchema = z.enum([
    "none",
    "firebase",
    "supabase",
    "appwrite",
    "customRest",
])
export type BackendProvider = z.infer<typeof backendProviderSchema>

export const architectureSchema = z.enum([
    "mvc",
    "mvvm",
    "clean",
    "feature-first",
    "layer-first",
])
export type ArchitectureStyle = z.infer<typeof architectureSchema>

export type StepId =
    | "basics"
    | "theme"
    | "state"
    | "backend"
    | "packages"
    | "architecture"
    | "extras"
    | "generate"

export const stepOrder: StepId[] = [
    "basics",
    "theme",
    "state",
    "backend",
    "packages",
    "architecture",
    "extras",
    "generate",
]

const fontSchema = z.object({
    choice: z.enum(["default", "google"]),
    family: z.string().optional(),
})
export type FontChoice = z.infer<typeof fontSchema>

const darkModeSchema = z.object({
    enabled: z.boolean(),
    system: z.boolean(),
})

const themeSchema = z.object({
    preset: themePresetSchema,
    primaryColor: z.string().optional(),
    darkMode: darkModeSchema,
    font: fontSchema,
})
export type ThemeConfig = z.infer<typeof themeSchema>

const firebaseSchema = z.object({
    authEmail: z.boolean(),
    authGoogle: z.boolean(),
    authPhone: z.boolean(),
    firestore: z.boolean(),
    realtimeDb: z.boolean(),
    storage: z.boolean(),
    analytics: z.boolean(),
    crashlytics: z.boolean(),
})

const supabaseSchema = z.object({
    auth: z.boolean(),
    database: z.boolean(),
    edgeFunctions: z.boolean(),
})

const appwriteSchema = z.object({
    auth: z.boolean(),
    database: z.boolean(),
    storage: z.boolean(),
})

const customRestSchema = z.object({
    baseUrl: z.string().optional(),
})

const backendSchema = z.discriminatedUnion("provider", [
    z.object({ provider: z.literal("none") }),
    z.object({ provider: z.literal("firebase"), options: firebaseSchema }),
    z.object({ provider: z.literal("supabase"), options: supabaseSchema }),
    z.object({ provider: z.literal("appwrite"), options: appwriteSchema }),
    z.object({ provider: z.literal("customRest"), options: customRestSchema }),
])
export type BackendConfig = z.infer<typeof backendSchema>

const packagesSchema = z.object({
    goRouter: z.boolean(),
    autoRoute: z.boolean(),
    dio: z.boolean(),
    http: z.boolean(),
    freezed: z.boolean(),
    jsonSerializable: z.boolean(),
    intl: z.boolean(),
    hive: z.boolean(),
    sharedPreferences: z.boolean(),
    flutterDotenv: z.boolean(),
    logger: z.boolean(),
})
export type PackagesConfig = z.infer<typeof packagesSchema>

const extrasSchema = z.object({
    localization: z.boolean(),
    errorHandling: z.boolean(),
    loadingStates: z.boolean(),
    networkConnectivity: z.boolean(),
    baseWidgets: z.boolean(),
    splashScreen: z.boolean(),
    appIcon: z.boolean(),
    flavors: z.boolean(),
})
export type ExtrasConfig = z.infer<typeof extrasSchema>

export const scaffoldConfigSchema = z.object({
    appName: z.string().min(1, "App name is required"),
    packageId: z.string().min(1, "Package id is required"),
    description: z.string().optional(),
    theme: themeSchema,
    stateManagement: stateManagementSchema,
    backend: backendSchema,
    commonPackages: packagesSchema,
    architecture: architectureSchema,
    extras: extrasSchema,
})

export type ScaffoldConfig = z.infer<typeof scaffoldConfigSchema>

export function derivePackageId(appName: string) {
    const cleaned = appName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "_")
        .replace(/^_+|_+$/g, "")

    if (!cleaned) {
        return "com.example.app"
    }

    return `com.example.${cleaned}`
}

export const defaultConfig: ScaffoldConfig = {
    appName: "Flutter Starter",
    packageId: derivePackageId("Flutter Starter"),
    description: "Production-ready Flutter scaffold generated by the wizard.",
    theme: {
        preset: "material3",
        primaryColor: "#6750A4",
        darkMode: { enabled: true, system: true },
        font: { choice: "default", family: "Roboto" },
    },
    stateManagement: "riverpod",
    backend: { provider: "none" },
    commonPackages: {
        goRouter: true,
        autoRoute: false,
        dio: true,
        http: false,
        freezed: false,
        jsonSerializable: true,
        intl: true,
        hive: false,
        sharedPreferences: true,
        flutterDotenv: true,
        logger: true,
    },
    architecture: "feature-first",
    extras: {
        localization: true,
        errorHandling: true,
        loadingStates: true,
        networkConnectivity: true,
        baseWidgets: true,
        splashScreen: true,
        appIcon: false,
        flavors: true,
    },
}

export function defaultBackendConfig(
    provider: BackendProvider = "none"
): BackendConfig {
    switch (provider) {
        case "firebase":
            return {
                provider: "firebase",
                options: {
                    authEmail: true,
                    authGoogle: true,
                    authPhone: false,
                    firestore: true,
                    realtimeDb: false,
                    storage: true,
                    analytics: true,
                    crashlytics: true,
                },
            }
        case "supabase":
            return {
                provider: "supabase",
                options: { auth: true, database: true, edgeFunctions: true },
            }
        case "appwrite":
            return {
                provider: "appwrite",
                options: { auth: true, database: true, storage: true },
            }
        case "customRest":
            return { provider: "customRest", options: { baseUrl: "" } }
        case "none":
        default:
            return { provider: "none" }
    }
}

export const backendOptions = [
    { value: "none", label: "None" },
    { value: "firebase", label: "Firebase" },
    { value: "supabase", label: "Supabase" },
    { value: "appwrite", label: "Appwrite" },
    { value: "customRest", label: "Custom REST" },
] as const satisfies Array<{ value: BackendProvider; label: string }>

export const stateManagementOptions = [
    { value: "provider", label: "Provider" },
    { value: "riverpod", label: "Riverpod" },
    { value: "bloc", label: "Bloc" },
    { value: "getx", label: "GetX" },
    { value: "mobx", label: "MobX" },
    { value: "none", label: "None (setState)" },
] as const satisfies Array<{ value: StateManagement; label: string }>

export const architectureOptions = [
    { value: "mvc", label: "MVC" },
    { value: "mvvm", label: "MVVM" },
    { value: "clean", label: "Clean Architecture" },
    { value: "feature-first", label: "Feature-first" },
    { value: "layer-first", label: "Layer-first" },
] as const satisfies Array<{ value: ArchitectureStyle; label: string }>

export const packageOptions: Array<{
    key: keyof PackagesConfig
    label: string
    description?: string
}> = [
        { key: "goRouter", label: "go_router" },
        { key: "autoRoute", label: "auto_route" },
        { key: "dio", label: "dio" },
        { key: "http", label: "http" },
        { key: "freezed", label: "freezed" },
        { key: "jsonSerializable", label: "json_serializable" },
        { key: "intl", label: "intl" },
        { key: "hive", label: "hive" },
        { key: "sharedPreferences", label: "shared_preferences" },
        { key: "flutterDotenv", label: "flutter_dotenv" },
        { key: "logger", label: "logger" },
    ]

export const extrasOptions: Array<{
    key: keyof ExtrasConfig
    label: string
    description?: string
}> = [
        { key: "localization", label: "Localization (i18n)" },
        { key: "errorHandling", label: "Error handling setup" },
        { key: "loadingStates", label: "Loading & empty states" },
        { key: "networkConnectivity", label: "Network connectivity checker" },
        { key: "baseWidgets", label: "Base widgets (Button, TextField)" },
        { key: "splashScreen", label: "Splash screen" },
        { key: "appIcon", label: "App icon" },
        { key: "flavors", label: "Flavors (dev/staging/prod)" },
    ]
